# Generated by Django 3.1.7 on 2021-03-31 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productdetail',
            table='product_detail',
        ),
    ]
