# Generated by Django 3.1.7 on 2021-04-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210401_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='url',
        ),
    ]
